services:
  react:
    container_name: sintube-ui
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: sintube-ui:latest
    ports:
      - "3001:3002"
    networks:
      - hls-network

networks:
  hls-network:
    external: true